
module.exports = {
  "met": { zh: "和/用", example: { dutch: "Ik ga met de trein.", en: "I go by train.", zh: "我坐火车去。" } },
  "van": { zh: "从/属于", example: { dutch: "Deze tas is van mij.", en: "This bag is mine.", zh: "这个包是我的。" } },
  "naar": { zh: "去/向", example: { dutch: "Ik ga naar huis.", en: "I am going home.", zh: "我回家。" } },
  "in": { zh: "在...里面", example: { dutch: "Ik woon in Amsterdam.", en: "I live in Amsterdam.", zh: "我住在阿姆斯特丹。" } },
  "voor": { zh: "在...前面/为了", example: { dutch: "De auto staat voor het huis.", en: "The car is in front of the house.", zh: "车在房子前面。" } },
  "achter": { zh: "在...后面", example: { dutch: "De tuin is achter het huis.", en: "The garden is behind the house.", zh: "花园在房子后面。" } },
  "naast": { zh: "在...旁边", example: { dutch: "Hij zit naast mij.", en: "He sits next to me.", zh: "他坐在我旁边。" } },
  "beneden": { zh: "楼下/下面", example: { dutch: "De keuken is beneden.", en: "The kitchen is downstairs.", zh: "厨房在楼下。" } },
  "boven": { zh: "楼上/上面", example: { dutch: "De slaapkamers zijn boven.", en: "The bedrooms are upstairs.", zh: "卧室在楼上。" } },
  "onder": { zh: "在...下面", example: { dutch: "De kat zit onder de tafel.", en: "The cat is under the table.", zh: "猫在桌子下面。" } },
  "op": { zh: "在...上面", example: { dutch: "Het boek ligt op de tafel.", en: "The book is on the table.", zh: "书在桌子上。" } },
  "tussen": { zh: "在...中间", example: { dutch: "Ik zit tussen Jan en Piet.", en: "I sit between Jan and Piet.", zh: "我坐在 Jan 和 Piet 中间。" } },
  "midden": { zh: "中间", example: { dutch: "In het midden van de kamer.", en: "In the middle of the room.", zh: "在房间中间。" } },
  "over": { zh: "关于/越过", example: { dutch: "We praten over het weer.", en: "We talk about the weather.", zh: "我们谈论天气。" } },
  "bij": { zh: "在...附近/处", example: { dutch: "Ik ben bij de dokter.", en: "I am at the doctor.", zh: "我在医生那里。" } },
  "binnen": { zh: "里面", example: { dutch: "Het is koud, ga naar binnen.", en: "It is cold, go inside.", zh: "很冷，进去吧。" } },
  "buiten": { zh: "外面", example: { dutch: "De kinderen spelen buiten.", en: "The children play outside.", zh: "孩子们在外面玩。" } },
  "tegen": { zh: "反对/对着", example: { dutch: "Hij leunt tegen de muur.", en: "He leans against the wall.", zh: "他靠着墙。" } },
  "rond": { zh: "周围", example: { dutch: "We lopen rond het meer.", en: "We walk around the lake.", zh: "我们绕着湖走。" } },
  "sinds": { zh: "自从", example: { dutch: "Ik woon hier sinds 2010.", en: "I live here since 2010.", zh: "我从2010年住在这里。" } },
  "zonder": { zh: "没有", example: { dutch: "Ik drink koffie zonder suiker.", en: "I drink coffee without sugar.", zh: "我喝咖啡不加糖。" } },
  "na": { zh: "在...之后", example: { dutch: "Na het eten ga ik slapen.", en: "After dinner I go to sleep.", zh: "晚饭后我去睡觉。" } },
  "om": { zh: "在(时间)/为了", example: { dutch: "De film begint om acht uur.", en: "The movie starts at eight o'clock.", zh: "电影八点开始。" } },
  "hoe-laat": { zh: "几点？", example: { dutch: "Hoe laat kom je?", en: "What time are you coming?", zh: "你几点来？" } },
  "hoe-laat-is-het": { zh: "现在几点了？", example: { dutch: "Weet jij hoe laat het is?", en: "Do you know what time it is?", zh: "你知道现在几点了吗？" } },
  "klok": { zh: "钟", example: { dutch: "De klok hangt aan de muur.", en: "The clock hangs on the wall.", zh: "钟挂在墙上。" } },
  "uur": { zh: "小时/点钟", example: { dutch: "Het duurt een uur.", en: "It takes an hour.", zh: "这需要一个小时。" } },
  "twee-uur": { zh: "两点", example: { dutch: "Het is twee uur.", en: "It is two o'clock.", zh: "现在是两点。" } },
  "om-tien-uur": { zh: "在十点", example: { dutch: "Ik heb een afspraak om tien uur.", en: "I have an appointment at ten o'clock.", zh: "我十点有个约会。" } },
  "half-vier": { zh: "三点半", example: { dutch: "Het is half vier.", en: "It is half past three.", zh: "现在是三点半。" } },
  "half-een": { zh: "十二点半", example: { dutch: "We lunchen om half een.", en: "We have lunch at half past twelve.", zh: "我们十二点半吃午饭。" } },
  "kwartier": { zh: "一刻钟", example: { dutch: "Ik wacht al een kwartier.", en: "I have been waiting for a quarter of an hour.", zh: "我已经等了一刻钟了。" } },
  "kwart-over-drie": { zh: "三点一刻", example: { dutch: "Het is kwart over drie.", en: "It is quarter past three.", zh: "现在是三点一刻。" } },
  "kwart-voor-zeven": { zh: "六点三刻", example: { dutch: "Het is kwart voor zeven.", en: "It is quarter to seven.", zh: "现在是六点四十五（差一刻七点）。" } },
  "minuut": { zh: "分钟", example: { dutch: "Wacht een minuut.", en: "Wait a minute.", zh: "等一分钟。" } },
  "tien-over-zes": { zh: "六点十分", example: { dutch: "De trein vertrekt om tien over zes.", en: "The train leaves at ten past six.", zh: "火车六点十分开。" } },
  "vijf-voor-acht": { zh: "七点五十五", example: { dutch: "Het is vijf voor acht.", en: "It is five to eight.", zh: "现在是七点五十五（差五分八点）。" } },
  "vijf-voor-half-zeven": { zh: "六点二十五", example: { dutch: "Het is vijf voor half zeven.", en: "It is twenty five past six.", zh: "现在是六点二十五。" } },
  "vijf-over-half-vier": { zh: "三点三十五", example: { dutch: "Het is vijf over half vier.", en: "It is twenty five to four.", zh: "现在是三点三十五。" } },
  "twintig-voor-vijf": { zh: "四点四十", example: { dutch: "Het is twintig voor vijf.", en: "It is twenty to five.", zh: "现在是四点四十。" } },
  "hoe-lang": { zh: "多久？", example: { dutch: "Hoe lang duurt de film?", en: "How long does the movie last?", zh: "电影多长时间？" } },
  "duurt-drie-uur": { zh: "持续三小时", example: { dutch: "De reis duurt drie uur.", en: "The journey takes three hours.", zh: "旅程需要三个小时。" } },
  "van-twee-uur-tot-vijf-uur": { zh: "从两点到五点", example: { dutch: "De winkel is open van twee uur tot vijf uur.", en: "The shop is open from two till five o'clock.", zh: "商店从两点开到五点。" } },
  "nacht": { zh: "夜晚", example: { dutch: "Goede nacht.", en: "Good night.", zh: "晚安。" } },
  "s-nachts": { zh: "在夜里", example: { dutch: "'s Nachts slaap ik.", en: "At night I sleep.", zh: "我在夜里睡觉。" } },
  "ochtend-de-morgen": { zh: "早晨", example: { dutch: "De ochtend is fris.", en: "The morning is fresh.", zh: "早晨很清爽。" } },
  "s-ochtends-s-morgens": { zh: "在早上", example: { dutch: "'s Ochtends eet ik brood.", en: "In the morning I eat bread.", zh: "早上我吃面包。" } },
  "middag": { zh: "下午", example: { dutch: "Goedemiddag.", en: "Good afternoon.", zh: "下午好。" } },
  "s-middags": { zh: "在下午", example: { dutch: "'s Middags werk ik.", en: "In the afternoon I work.", zh: "下午我工作。" } },
  "s-avonds": { zh: "在晚上", example: { dutch: "'s Avonds kijk ik tv.", en: "In the evening I watch TV.", zh: "晚上我看电视。" } },
  "kwart-voor-zeven-s-ochtends": { zh: "早上六点四十五", example: { dutch: "Ik sta op om kwart voor zeven 's ochtends.", en: "I get up at quarter to seven am.", zh: "我早上六点四十五起床。" } },
  "middernacht": { zh: "午夜", example: { dutch: "Het is middernacht.", en: "It is midnight.", zh: "现在是午夜。" } },
  "twaalf-uur-s-middags": { zh: "中午十二点", example: { dutch: "We lunchen om twaalf uur 's middags.", en: "We have lunch at noon.", zh: "我们中午十二点吃午饭。" } },
  "vrije-tijd": { zh: "空闲时间", example: { dutch: "Wat doe je in je vrije tijd?", en: "What do you do in your leisure time?", zh: "你空闲时间做什么？" } },
  "hobby": { zh: "爱好", example: { dutch: "Mijn hobby is lezen.", en: "My hobby is reading.", zh: "我的爱好是读书。" } },
  "reizen": { zh: "旅行", example: { dutch: "Ik hou van reizen.", en: "I love to travel.", zh: "我喜欢旅行。" } },
  "vakantie": { zh: "假期", example: { dutch: "We gaan op vakantie naar Spanje.", en: "We are going on holiday to Spain.", zh: "我们去西班牙度假。" } },
  "kamperen": { zh: "露营", example: { dutch: "We gaan kamperen in het bos.", en: "We are going to camp in the forest.", zh: "我们要去森林露营。" } },
  "strand": { zh: "海滩", example: { dutch: "Het strand is mooi.", en: "The beach is beautiful.", zh: "海滩很美。" } },
  "zonnen": { zh: "晒日光浴", example: { dutch: "Zij ligt te zonnen.", en: "She is sunbathing.", zh: "她在晒日光浴。" } },
  "pretpark": { zh: "游乐园", example: { dutch: "De Efteling is een pretpark.", en: "The Efteling is a theme park.", zh: "Efteling 是一个游乐园。" } },
  "tuinieren": { zh: "园艺", example: { dutch: "Mijn vader houdt van tuinieren.", en: "My father loves gardening.", zh: "我父亲喜欢园艺。" } },
  "taal": { zh: "语言", example: { dutch: "Nederlands is een moeilijke taal.", en: "Dutch is a difficult language.", zh: "荷兰语是一门难学的语言。" } },
  "een-taal-leren": { zh: "学习一门语言", example: { dutch: "Ik wil een nieuwe taal leren.", en: "I want to learn a new language.", zh: "我想学一门新语言。" } },
  "sporten": { zh: "运动", example: { dutch: "Ik sport twee keer per week.", en: "I exercise twice a week.", zh: "我每周运动两次。" } },
  "hardlopen": { zh: "跑步", example: { dutch: "Hij gaat elke ochtend hardlopen.", en: "He goes running every morning.", zh: "他每天早上跑步。" } },
  "wandelen": { zh: "散步/徒步", example: { dutch: "Wij wandelen in het park.", en: "We are walking in the park.", zh: "我们在公园散步。" } },
  "tennissen": { zh: "打网球", example: { dutch: "Kun jij tennissen?", en: "Can you play tennis?", zh: "你会打网球吗？" } },
  "hockeyen": { zh: "打曲棍球", example: { dutch: "Hockeyen is populair in Nederland.", en: "Hockey is popular in the Netherlands.", zh: "曲棍球在荷兰很受欢迎。" } },
  "borrelen": { zh: "喝一杯(社交)", example: { dutch: "Vrijdagmiddag gaan we borrelen.", en: "Friday afternoon we go for a drink.", zh: "周五下午我们去喝一杯。" } },
  "uit-eten-gaan": { zh: "出去吃饭", example: { dutch: "Zullen we uit eten gaan?", en: "Shall we go out for dinner?", zh: "我们要不要出去吃饭？" } },
  "uitgaan": { zh: "外出/娱乐", example: { dutch: "Jongeren gaan graag uitgaan.", en: "Young people like to go out.", zh: "年轻人喜欢出去玩。" } },
  "stappen": { zh: "出去玩(泡吧)", example: { dutch: "We gaan vanavond stappen.", en: "We are going out tonight.", zh: "我们今晚去泡吧。" } },
  "dronken-zijn": { zh: "喝醉", example: { dutch: "Hij is een beetje dronken.", en: "He is a bit drunk.", zh: "他有点醉了。" } },
  "koken": { zh: "做饭", example: { dutch: "Ik kook vanavond.", en: "I cook tonight.", zh: "今晚我做饭。" } },
  "kunst": { zh: "艺术", example: { dutch: "Ik hou van moderne kunst.", en: "I love modern art.", zh: "我喜欢现代艺术。" } },
  "verjaardag": { zh: "生日", example: { dutch: "Gefeliciteerd met je verjaardag!", en: "Happy birthday!", zh: "生日快乐！" } },
  "een-verjaardag-vieren": { zh: "庆祝生日", example: { dutch: "Hoe ga je je verjaardag vieren?", en: "How are you going to celebrate your birthday?", zh: "你打算怎么庆祝生日？" } },
  "hij-is-jarig": { zh: "他过生日", example: { dutch: "Vandaag is hij jarig.", en: "Today is his birthday.", zh: "今天他过生日。" } },
  "zingen": { zh: "唱歌", example: { dutch: "Zij kan mooi zingen.", en: "She can sing beautifully.", zh: "她唱歌很好听。" } },
  "dansen": { zh: "跳舞", example: { dutch: "Wil je dansen?", en: "Do you want to dance?", zh: "你想跳舞吗？" } },
  "winkelen": { zh: "购物", example: { dutch: "Ik ga winkelen in de stad.", en: "I am going shopping in the city.", zh: "我去城里购物。" } },
  "amsterdam": { zh: "阿姆斯特丹", example: { dutch: "Amsterdam is de hoofdstad.", en: "Amsterdam is the capital.", zh: "阿姆斯特丹是首都。" } },
  "gracht": { zh: "运河", example: { dutch: "De grachten zijn mooi.", en: "The canals are beautiful.", zh: "运河很美。" } },
  "grachtenpand": { zh: "运河房屋", example: { dutch: "Een grachtenpand is duur.", en: "A canal house is expensive.", zh: "运河边的房子很贵。" } },
  "woonboot": { zh: "船屋", example: { dutch: "Hij woont op een woonboot.", en: "He lives on a houseboat.", zh: "他住在船屋上。" } },
  "wonen": { zh: "居住", example: { dutch: "Waar woon jij?", en: "Where do you live?", zh: "你住哪儿？" } },
  "paleis": { zh: "宫殿", example: { dutch: "Het koninklijk paleis staat in Amsterdam.", en: "The royal palace is in Amsterdam.", zh: "皇宫在阿姆斯特丹。" } },
  "pont": { zh: "渡轮", example: { dutch: "Neem de pont naar Noord.", en: "Take the ferry to North.", zh: "坐渡轮去北边。" } },
  "rondvaart": { zh: "运河游船", example: { dutch: "Toeristen maken een rondvaart.", en: "Tourists take a canal cruise.", zh: "游客乘坐运河游船。" } },
  "museum": { zh: "博物馆", example: { dutch: "Het Rijksmuseum is groot.", en: "The Rijksmuseum is big.", zh: "国家博物馆很大。" } },
  "concert": { zh: "音乐会", example: { dutch: "We gaan naar een concert.", en: "We are going to a concert.", zh: "我们要去听音乐会。" } },
  "gebouw": { zh: "建筑物", example: { dutch: "Dat is een hoog gebouw.", en: "That is a tall building.", zh: "那是一座高楼。" } },
  "concertgebouw": { zh: "音乐厅", example: { dutch: "Het Concertgebouw heeft goede akoestiek.", en: "The Concertgebouw has good acoustics.", zh: "音乐厅音响效果很好。" } },
  "plein": { zh: "广场", example: { dutch: "De Dam is een bekend plein.", en: "Dam Square is a famous square.", zh: "水坝广场是个著名的广场。" } },
  "fietspad": { zh: "自行车道", example: { dutch: "Fiets op het fietspad.", en: "Cycle on the bicycle track.", zh: "在自行车道上骑车。" } },
  "brug": { zh: "桥", example: { dutch: "Amsterdam heeft veel bruggen.", en: "Amsterdam has many bridges.", zh: "阿姆斯特丹有很多桥。" } },
  "eiland": { zh: "岛屿", example: { dutch: "Texel is een eiland.", en: "Texel is an island.", zh: "特塞尔是一个岛。" } },
  "ring": { zh: "环路/戒指", example: { dutch: "De ring A10 is druk.", en: "The ring road A10 is busy.", zh: "A10环路很繁忙。" } },
  "coffeeshop": { zh: "大麻咖啡馆", example: { dutch: "In een coffeeshop koop je softdrugs.", en: "In a coffeeshop you buy soft drugs.", zh: "在coffeeshop可以买软毒品。" } },
  "stadion": { zh: "体育场", example: { dutch: "Ajax speelt in het stadion.", en: "Ajax plays in the stadium.", zh: "阿贾克斯在体育场比赛。" } },
  "hoofdkantoor": { zh: "总部", example: { dutch: "Het hoofdkantoor staat in Den Haag.", en: "The head office is in The Hague.", zh: "总部在海牙。" } },
  "wallen": { zh: "红灯区", example: { dutch: "De Wallen zijn in het centrum.", en: "The Red Light District is in the center.", zh: "红灯区在市中心。" } },
  "hoer": { zh: "妓女", example: { dutch: "Dat is een beroep.", en: "That is a profession.", zh: "那是一个职业。" } },
  "park": { zh: "公园", example: { dutch: "Het Vondelpark is gezellig.", en: "The Vondelpark is cozy.", zh: "冯德尔公园很惬意。" } },
  "bos": { zh: "森林", example: { dutch: "We wandelen in het bos.", en: "We walk in the forest.", zh: "我们在森林里散步。" } },
  "woning": { zh: "住宅", example: { dutch: "Ik zoek een nieuwe woning.", en: "I am looking for a new house.", zh: "我在找新房子。" } },
  "deur": { zh: "门", example: { dutch: "Doe de deur dicht.", en: "Close the door.", zh: "把门关上。" } },
  "raam": { zh: "窗户", example: { dutch: "Het raam staat open.", en: "The window is open.", zh: "窗户开着。" } },
  "stoel": { zh: "椅子", example: { dutch: "Ga op de stoel zitten.", en: "Sit on the chair.", zh: "坐在椅子上。" } },
  "kruk": { zh: "凳子", example: { dutch: "De kruk is laag.", en: "The stool is low.", zh: "凳子很矮。" } },
  "tafel": { zh: "桌子", example: { dutch: "Het eten staat op tafel.", en: "The food is on the table.", zh: "食物在桌子上。" } },
  "lamp": { zh: "灯", example: { dutch: "Doe de lamp aan.", en: "Turn on the lamp.", zh: "把灯打开。" } },
  "televisie": { zh: "电视", example: { dutch: "We kijken televisie.", en: "We are watching television.", zh: "我们在看电视。" } },
  "kast": { zh: "柜子", example: { dutch: "De kleren liggen in de kast.", en: "The clothes are in the closet.", zh: "衣服在柜子里。" } },
  "wc": { zh: "厕所", example: { dutch: "Mag ik naar de wc?", en: "May I go to the toilet?", zh: "我可以去厕所吗？" } },
  "keuken": { zh: "厨房", example: { dutch: "Ik kook in de keuken.", en: "I cook in the kitchen.", zh: "我在厨房做饭。" } },
  "fornuis": { zh: "炉灶", example: { dutch: "Het fornuis is heet.", en: "The stove is hot.", zh: "炉灶很热。" } },
  "koelkast": { zh: "冰箱", example: { dutch: "De melk staat in de koelkast.", en: "The milk is in the fridge.", zh: "牛奶在冰箱里。" } },
  "kamer": { zh: "房间", example: { dutch: "Ik heb een eigen kamer.", en: "I have my own room.", zh: "我有自己的房间。" } },
  "woonkamer": { zh: "客厅", example: { dutch: "We zitten in de woonkamer.", en: "We are sitting in the living room.", zh: "我们坐在客厅里。" } },
  "bank": { zh: "沙发/银行", example: { dutch: "De bank zit lekker.", en: "The couch sits comfortably.", zh: "沙发坐着很舒服。" } },
  "slaapkamer": { zh: "卧室", example: { dutch: "Het bed staat in de slaapkamer.", en: "The bed is in the bedroom.", zh: "床在卧室里。" } },
  "bed": { zh: "床", example: { dutch: "Ik lig in bed.", en: "I am lying in bed.", zh: "我躺在床上。" } },
  "badkamer": { zh: "浴室", example: { dutch: "Ik poets mijn tanden in de badkamer.", en: "I brush my teeth in the bathroom.", zh: "我在浴室刷牙。" } },
  "douche": { zh: "淋浴", example: { dutch: "Ik neem een douche.", en: "I take a shower.", zh: "我洗个澡。" } },
  "bad": { zh: "浴缸", example: { dutch: "Ik ga in bad.", en: "I take a bath.", zh: "我泡澡。" } },
  "bijkeuken": { zh: "杂物间", example: { dutch: "De wasmachine staat in de bijkeuken.", en: "The washing machine is in the utility room.", zh: "洗衣机在杂物间。" } },
  "garage": { zh: "车库", example: { dutch: "De auto staat in de garage.", en: "The car is in the garage.", zh: "车在车库里。" } },
  "tuin": { zh: "花园", example: { dutch: "We zitten in de tuin.", en: "We sit in the garden.", zh: "我们坐在花园里。" } },
  "zolder": { zh: "阁楼", example: { dutch: "De dozen staan op zolder.", en: "The boxes are in the attic.", zh: "箱子在阁楼上。" } },
  "lichaam": { zh: "身体", example: { dutch: "Sporten is goed voor je lichaam.", en: "Exercise is good for your body.", zh: "运动对身体有好处。" } },
  "lijf": { zh: "身体(口语)", example: { dutch: "Mijn hele lijf doet pijn.", en: "My whole body hurts.", zh: "我浑身都疼。" } },
  "hoofd": { zh: "头", example: { dutch: "Ik heb pijn in mijn hoofd.", en: "I have a pain in my head.", zh: "我头疼。" } },
  "kop": { zh: "头(动物/口语)", example: { dutch: "Kop dicht! (rude)", en: "Shut up!", zh: "闭嘴！(粗鲁)" } },
  "mond": { zh: "嘴", example: { dutch: "Doe je mond open.", en: "Open your mouth.", zh: "张开嘴。" } },
  "tand": { zh: "牙齿", example: { dutch: "Ik poets mijn tanden.", en: "I brush my teeth.", zh: "我刷牙。" } },
  "oor": { zh: "耳朵", example: { dutch: "Ik hoor het met mijn oor.", en: "I hear it with my ear.", zh: "我用耳朵听。" } },
  "oog": { zh: "眼睛", example: { dutch: "Zij heeft blauwe ogen.", en: "She has blue eyes.", zh: "她有蓝眼睛。" } },
  "bril": { zh: "眼镜", example: { dutch: "Ik draag een bril.", en: "I wear glasses.", zh: "我戴眼镜。" } },
  "zonnebril": { zh: "太阳镜", example: { dutch: "De zon schijnt, ik zet mijn zonnebril op.", en: "The sun is shining, I put on my sunglasses.", zh: "阳光明媚，我戴上太阳镜。" } },
  "neus": { zh: "鼻子", example: { dutch: "Ik ruik met mijn neus.", en: "I smell with my nose.", zh: "我用鼻子闻。" } },
  "haar": { zh: "头发", example: { dutch: "Zij heeft lang haar.", en: "She has long hair.", zh: "她有长头发。" } },
  "arm": { zh: "手臂", example: { dutch: "Mijn arm is gebroken.", en: "My arm is broken.", zh: "我的手臂断了。" } },
  "elleboog": { zh: "手肘", example: { dutch: "Ik stootte mijn elleboog.", en: "I bumped my elbow.", zh: "我撞到了手肘。" } },
  "hand": { zh: "手", example: { dutch: "Geef me een hand.", en: "Give me a hand.", zh: "帮我一把/握手。" } },
  "vinger": { zh: "手指", example: { dutch: "Ik heb vijf vingers aan één hand.", en: "I have five fingers on one hand.", zh: "我一只手有五个手指。" } },
  "been": { zh: "腿", example: { dutch: "Hij heeft lange benen.", en: "He has long legs.", zh: "他有长腿。" } },
  "knie": { zh: "膝盖", example: { dutch: "Ik heb last van mijn knie.", en: "I have trouble with my knee.", zh: "我膝盖不舒服。" } },
  "voet": { zh: "脚", example: { dutch: "Deze schoen past niet aan mijn voet.", en: "This shoe does not fit my foot.", zh: "这只鞋不合我的脚。" } },
  "teen": { zh: "脚趾", example: { dutch: "Ik stootte mijn teen.", en: "I stubbed my toe.", zh: "我踢到了脚趾。" } },
  "rug": { zh: "背", example: { dutch: "Ik heb rugpijn.", en: "I have back pain.", zh: "我背疼。" } },
  "buik": { zh: "肚子", example: { dutch: "Ik heb buikpijn.", en: "I have a stomach ache.", zh: "我肚子疼。" } },
  "schouder": { zh: "肩膀", example: { dutch: "Klop hem op de schouder.", en: "Pat him on the shoulder.", zh: "拍拍他的肩膀。" } },
  "kont": { zh: "屁股", example: { dutch: "Ga op je kont zitten.", en: "Sit on your butt.", zh: "坐下。" } },
  "borst": { zh: "胸部", example: { dutch: "Hij heeft haar op zijn borst.", en: "He has hair on his chest.", zh: "他胸口有毛。" } },
  "baard": { zh: "胡子", example: { dutch: "De man heeft een baard.", en: "The man has a beard.", zh: "那个男人有胡子。" } },
  "snor": { zh: "小胡子", example: { dutch: "Hij laat zijn snor staan.", en: "He is growing his moustache.", zh: "他在留小胡子。" } },
  "hart": { zh: "心脏", example: { dutch: "Mijn hart klopt snel.", en: "My heart beats fast.", zh: "我的心跳得很快。" } },
  "kleren": { zh: "衣服", example: { dutch: "Ik koop nieuwe kleren.", en: "I buy new clothes.", zh: "我买新衣服。" } },
  "kleding": { zh: "服装", example: { dutch: "Draag warme kleding.", en: "Wear warm clothing.", zh: "穿暖和的衣服。" } },
  "kledingwinkel": { zh: "服装店", example: { dutch: "De kledingwinkel is open.", en: "The clothes shop is open.", zh: "服装店开门了。" } },
  "broek": { zh: "裤子", example: { dutch: "Deze broek is te lang.", en: "These pants are too long.", zh: "这条裤子太长了。" } },
  "spijkerbroek": { zh: "牛仔裤", example: { dutch: "Ik draag graag een spijkerbroek.", en: "I like wearing jeans.", zh: "我喜欢穿牛仔裤。" } },
  "trui": { zh: "毛衣/卫衣", example: { dutch: "In de winter draag ik een trui.", en: "In winter I wear a sweater.", zh: "冬天我穿毛衣。" } },
  "jas": { zh: "外套", example: { dutch: "Doe je jas aan, het is koud.", en: "Put on your coat, it is cold.", zh: "穿上外套，外面冷。" } },
  "rok": { zh: "裙子", example: { dutch: "Zij draagt een rok.", en: "She wears a skirt.", zh: "她穿着裙子。" } },
  "jurk": { zh: "连衣裙", example: { dutch: "Wat een mooie jurk!", en: "What a beautiful dress!", zh: "多漂亮的连衣裙！" } },
  "sok": { zh: "袜子", example: { dutch: "Ik ben mijn sok kwijt.", en: "I lost my sock.", zh: "我丢了一只袜子。" } },
  "kous": { zh: "长袜", example: { dutch: "Kousen zijn lang.", en: "Stockings are long.", zh: "长袜很长。" } },
  "schoen": { zh: "鞋子", example: { dutch: "Trek je schoenen aan.", en: "Put on your shoes.", zh: "穿上鞋子。" } },
  "klomp": { zh: "木鞋", example: { dutch: "De boer draagt klompen.", en: "The farmer wears wooden shoes.", zh: "农民穿木鞋。" } },
  "riem": { zh: "腰带", example: { dutch: "Mijn broek zakt af, ik heb een riem nodig.", en: "My pants are falling down, I need a belt.", zh: "裤子老掉，我需要一条腰带。" } },
  "t-shirt": { zh: "T恤", example: { dutch: "In de zomer draag ik een T-shirt.", en: "In summer I wear a T-shirt.", zh: "夏天我穿T恤。" } },
  "onderhemd": { zh: "内衣/背心", example: { dutch: "Ik draag een hemd onder mijn trui.", en: "I wear an undershirt under my sweater.", zh: "我在毛衣里面穿背心。" } },
  "overhemd": { zh: "衬衫", example: { dutch: "Hij draagt een wit overhemd.", en: "He wears a white shirt.", zh: "他穿着白衬衫。" } },
  "blouse": { zh: "女衬衫", example: { dutch: "Zij heeft een zijden blouse.", en: "She has a silk blouse.", zh: "她有一件丝绸衬衫。" } },
  "pak": { zh: "西装", example: { dutch: "Naar zijn werk draagt hij een pak.", en: "He wears a suit to work.", zh: "他上班穿西装。" } },
  "het-de-colbert": { zh: "西装外套", example: { dutch: "Hij doet zijn colbert uit.", en: "He takes off his jacket.", zh: "他脱下西装外套。" } },
  "stropdas": { zh: "领带", example: { dutch: "Een rode stropdas.", en: "A red tie.", zh: "一条红领带。" } },
  "strik": { zh: "领结/蝴蝶结", example: { dutch: "Hij draagt een strik.", en: "He wears a bow tie.", zh: "他戴着领结。" } },
  "pyjama": { zh: "睡衣", example: { dutch: "Ik trek mijn pyjama aan.", en: "I put on my pajamas.", zh: "我穿上睡衣。" } },
  "onderbroek": { zh: "内裤", example: { dutch: "Schone onderbroek.", en: "Clean underwear.", zh: "干净的内裤。" } },
  "bh": { zh: "胸罩", example: { dutch: "Zij koopt een nieuwe bh.", en: "She buys a new bra.", zh: "她买了个新胸罩。" } },
  "hoed": { zh: "帽子", example: { dutch: "Zet je hoed op.", en: "Put on your hat.", zh: "戴上帽子。" } },
  "das": { zh: "围巾/领带", example: { dutch: "Ik draag een das in de winter.", en: "I wear a scarf in winter.", zh: "冬天我戴围巾。" } },
  "doen": { zh: "做", example: { dutch: "Wat ga je doen?", en: "What are you going to do?", zh: "你要做什么？" } },
  "beginnen": { zh: "开始", example: { dutch: "De les begint nu.", en: "The lesson starts now.", zh: "课现在开始。" } },
  "geloven": { zh: "相信", example: { dutch: "Ik geloof je.", en: "I believe you.", zh: "我相信你。" } },
  "brengen": { zh: "带去/送", example: { dutch: "Ik breng je naar huis.", en: "I take you home.", zh: "我送你回家。" } },
  "halen": { zh: "去拿/接", example: { dutch: "Ik ga boodschappen halen.", en: "I am going to get groceries.", zh: "我去买东西。" } },
  "lenen": { zh: "借", example: { dutch: "Mag ik een pen lenen?", en: "May I borrow a pen?", zh: "我可以借支笔吗？" } },
  "bellen": { zh: "打电话", example: { dutch: "Ik bel je later.", en: "I call you later.", zh: "我回头给你打电话。" } },
  "kunnen": { zh: "能/会", example: { dutch: "Ik kan zwemmen.", en: "I can swim.", zh: "我会游泳。" } },
  "sluiten": { zh: "关闭", example: { dutch: "De winkel sluit om zes uur.", en: "The shop closes at six.", zh: "商店六点关门。" } },
  "snijden": { zh: "切", example: { dutch: "Ik snijd het brood.", en: "I cut the bread.", zh: "我切面包。" } },
  "beslissen": { zh: "决定", example: { dutch: "Ik moet nu beslissen.", en: "I have to decide now.", zh: "我现在得决定。" } },
  "vallen": { zh: "掉落/摔倒", example: { dutch: "Het glas valt op de grond.", en: "The glass falls on the floor.", zh: "杯子掉地上了。" } },
  "voelen": { zh: "感觉/摸", example: { dutch: "Ik voel me goed.", en: "I feel good.", zh: "我感觉很好。" } },
  "volgen": { zh: "跟随", example: { dutch: "Volg mij maar.", en: "Follow me.", zh: "跟我来。" } },
  "gebeuren": { zh: "发生", example: { dutch: "Wat gebeurt er?", en: "What is happening?", zh: "发生什么了？" } },
  "iets": { zh: "某事/东西", example: { dutch: "Wil je iets drinken?", en: "Do you want something to drink?", zh: "你想喝点什么吗？" } },
  "helpen": { zh: "帮助", example: { dutch: "Kan ik je helpen?", en: "Can I help you?", zh: "我能帮你吗？" } },
  "houden": { zh: "保持/持有", example: { dutch: "Mag ik het houden?", en: "Can I keep it?", zh: "我可以留着它吗？" } },
  "houden-van": { zh: "爱/喜欢", example: { dutch: "Ik hou van jou.", en: "I love you.", zh: "我爱你。" } },
  "weten": { zh: "知道", example: { dutch: "Ik weet het niet.", en: "I don't know.", zh: "我不知道。" } },
  "kennen": { zh: "认识/了解", example: { dutch: "Ken jij hem?", en: "Do you know him?", zh: "你认识他吗？" } },
  "leuk-vinden": { zh: "喜欢", example: { dutch: "Ik vind het leuk.", en: "I like it.", zh: "我喜欢这个。" } },
  "laten": { zh: "让/留下", example: { dutch: "Laat me met rust.", en: "Leave me alone.", zh: "别烦我。" } },
  "verliezen": { zh: "输/丢失", example: { dutch: "Ik wil niet verliezen.", en: "I don't want to lose.", zh: "我不想输。" } },
  "winnen": { zh: "赢", example: { dutch: "Wij gaan winnen.", en: "We are going to win.", zh: "我们要赢了。" } },
  "maken": { zh: "制作/修理", example: { dutch: "Ik maak huiswerk.", en: "I do homework.", zh: "我做作业。" } },
  "solliciteren": { zh: "申请(工作)", example: { dutch: "Ik solliciteer naar deze baan.", en: "I apply for this job.", zh: "我申请这份工作。" } },
  "sollicitatie": { zh: "申请", example: { dutch: "Ik heb een sollicitatie verstuurd.", en: "I sent an application.", zh: "我发了一份申请。" } },
  "vacature": { zh: "空缺职位", example: { dutch: "Er is een vacature.", en: "There is a vacancy.", zh: "有个空缺职位。" } },
  "advertentie": { zh: "广告", example: { dutch: "Ik zag de advertentie in de krant.", en: "I saw the advertisement in the newspaper.", zh: "我在报纸上看到了广告。" } },
  "werk": { zh: "工作", example: { dutch: "Ik ga naar mijn werk.", en: "I go to work.", zh: "我去上班。" } },
  "baan": { zh: "工作/职位", example: { dutch: "Ik heb een leuke baan.", en: "I have a nice job.", zh: "我有份好工作。" } },
  "veranderen": { zh: "改变", example: { dutch: "Het weer verandert snel.", en: "The weather changes quickly.", zh: "天气变得很快。" } },
  "brief": { zh: "信", example: { dutch: "Ik schrijf een brief.", en: "I write a letter.", zh: "我写一封信。" } },
  "sollicitatiebrief": { zh: "求职信", example: { dutch: "De sollicitatiebrief is belangrijk.", en: "The application letter is important.", zh: "求职信很重要。" } },
  "cv-curriculum-vitae": { zh: "简历", example: { dutch: "Stuur je cv mee.", en: "Send your resume along.", zh: "附上你的简历。" } },
  "opleiding": { zh: "教育/培训", example: { dutch: "Welke opleiding heb je gedaan?", en: "What education did you do?", zh: "你受过什么教育？" } },
  "ervaring": { zh: "经验", example: { dutch: "Heb je ervaring?", en: "Do you have experience?", zh: "你有经验吗？" } },
  "gesprek": { zh: "谈话", example: { dutch: "We hebben een goed gesprek.", en: "We have a good conversation.", zh: "我们谈得很愉快。" } },
  "sollicitatiegesprek": { zh: "面试", example: { dutch: "Ik heb morgen een sollicitatiegesprek.", en: "I have a job interview tomorrow.", zh: "我明天有个面试。" } },
  "bedrijf": { zh: "公司", example: { dutch: "Het bedrijf groeit.", en: "The company is growing.", zh: "公司在成长。" } },
  "zaak": { zh: "生意/店铺", example: { dutch: "Hij heeft een eigen zaak.", en: "He has his own business.", zh: "他有自己的生意。" } },
  "salaris": { zh: "薪水", example: { dutch: "Het salaris is goed.", en: "The salary is good.", zh: "薪水不错。" } },
  "bruto": { zh: "毛(收入)", example: { dutch: "Bruto salaris.", en: "Gross salary.", zh: "毛薪。" } },
  "netto": { zh: "净(收入)", example: { dutch: "Netto salaris.", en: "Net salary.", zh: "净薪。" } },
  "belasting": { zh: "税", example: { dutch: "Je moet belasting betalen.", en: "You have to pay tax.", zh: "你得交税。" } },
  "vakantiegeld": { zh: "度假津贴", example: { dutch: "In mei krijg ik vakantiegeld.", en: "In May I get holiday allowance.", zh: "五月份我拿度假津贴。" } },
  "auto-van-de-zaak": { zh: "公司用车", example: { dutch: "Ik heb een auto van de zaak.", en: "I have a company car.", zh: "我有辆公司配车。" } },
  "pensioen": { zh: "养老金", example: { dutch: "Hij gaat met pensioen.", en: "He is retiring.", zh: "他退休了。" } },
  "reiskosten": { zh: "差旅费", example: { dutch: "De reiskosten zijn hoog.", en: "The travel expenses are high.", zh: "差旅费很高。" } },
  "vergoeding": { zh: "报销/补偿", example: { dutch: "Je krijgt een vergoeding.", en: "You get a compensation.", zh: "你会得到补偿。" } },
  "reiskostenvergoeding": { zh: "交通补贴", example: { dutch: "Ik krijg reiskostenvergoeding.", en: "I receive travel allowance.", zh: "我有交通补贴。" } },
  "collega": { zh: "同事", example: { dutch: "Mijn collega is aardig.", en: "My colleague is nice.", zh: "我的同事很友善。" } },
  "aannemen": { zh: "雇佣/接受", example: { dutch: "Ze gaan hem aannemen.", en: "They are going to hire him.", zh: "他们要录用他。" } },
  "ontslaan": { zh: "解雇", example: { dutch: "Hij is ontslagen.", en: "He was fired.", zh: "他被解雇了。" } },
  "vader": { zh: "父亲", example: { dutch: "Mijn vader is 50 jaar.", en: "My father is 50 years old.", zh: "我父亲50岁。" } },
  "papa": { zh: "爸爸", example: { dutch: "Papa, mag ik snoep?", en: "Dad, can I have candy?", zh: "爸爸，我可以吃糖吗？" } },
  "moeder": { zh: "母亲", example: { dutch: "Mijn moeder werkt hard.", en: "My mother works hard.", zh: "我母亲工作努力。" } },
  "mama": { zh: "妈妈", example: { dutch: "Mama kookt lekker.", en: "Mom cooks well.", zh: "妈妈做饭好吃。" } },
  "broer": { zh: "兄弟", example: { dutch: "Ik heb een broer.", en: "I have a brother.", zh: "我有个兄弟。" } },
  "zus": { zh: "姐妹", example: { dutch: "Mijn zus woont in Utrecht.", en: "My sister lives in Utrecht.", zh: "我姐妹住在乌特勒支。" } },
  "opa": { zh: "爷爷/外公", example: { dutch: "Opa vertelt een verhaal.", en: "Grandpa tells a story.", zh: "爷爷讲故事。" } },
  "oma": { zh: "奶奶/外婆", example: { dutch: "Oma bakt taart.", en: "Grandma bakes cake.", zh: "奶奶烤蛋糕。" } },
  "tante": { zh: "阿姨/姑姑", example: { dutch: "Mijn tante komt op bezoek.", en: "My aunt is coming to visit.", zh: "我阿姨来串门。" } },
  "oom": { zh: "叔叔/舅舅", example: { dutch: "Oom Jan is grappig.", en: "Uncle Jan is funny.", zh: "Jan叔叔很有趣。" } },
  "neef": { zh: "表/堂兄弟/侄子", example: { dutch: "Mijn neef is even oud als ik.", en: "My cousin is the same age as me.", zh: "我表兄弟和我一样大。" } },
  "nicht": { zh: "表/堂姐妹/侄女", example: { dutch: "Mijn nicht is jarig.", en: "My niece is having a birthday.", zh: "我表妹过生日。" } },
  "kind": { zh: "孩子", example: { dutch: "Het kind speelt.", en: "The child plays.", zh: "孩子在玩。" } },
  "kleinkind": { zh: "孙子/孙女", example: { dutch: "Zij is mijn kleinkind.", en: "She is my grandchild.", zh: "她是我的孙女。" } },
  "vriend": { zh: "男朋友/男性朋友", example: { dutch: "Dit is mijn vriend.", en: "This is my boyfriend/friend.", zh: "这是我男朋友/朋友。" } },
  "vriendin": { zh: "女朋友/女性朋友", example: { dutch: "Ik ga shoppen met een vriendin.", en: "I go shopping with a friend.", zh: "我和女朋友去逛街。" } },
  "kennis": { zh: "熟人/知识", example: { dutch: "Hij is een kennis van mij.", en: "He is an acquaintance of mine.", zh: "他是我的一个熟人。" } },
  "bekende": { zh: "熟人", example: { dutch: "Ik kwam een bekende tegen.", en: "I met an acquaintance.", zh: "我遇到了一个熟人。" } },
  "klasgenoot": { zh: "同学", example: { dutch: "Mijn klasgenoot helpt mij.", en: "My classmate helps me.", zh: "我同学帮我。" } },
  "verkering": { zh: "恋爱关系", example: { dutch: "Zij hebben verkering.", en: "They are in a relationship.", zh: "他们在谈恋爱。" } },
  "verliefd": { zh: "恋爱中/爱上", example: { dutch: "Ik ben verliefd op jou.", en: "I am in love with you.", zh: "我爱上你了。" } },
  "verloofd": { zh: "订婚", example: { dutch: "Wij zijn verloofd.", en: "We are engaged.", zh: "我们订婚了。" } },
  "trouwen": { zh: "结婚", example: { dutch: "Zij gaan trouwen.", en: "They are getting married.", zh: "他们要结婚了。" } },
  "scheiden": { zh: "离婚", example: { dutch: "Zij gaan scheiden.", en: "They are getting divorced.", zh: "他们要离婚了。" } },
  "gescheiden-zijn": { zh: "已离婚", example: { dutch: "Ik ben gescheiden.", en: "I am divorced.", zh: "我离婚了。" } }
};



